"""EA strategy generator with multi-factor signal generation."""
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple, Any
from datetime import datetime
import numpy as np
import pandas as pd

from app.core.factors.analyzer import FactorAnalyzer
from app.core.factors.library import FactorLibrary, get_factor_by_name
from app.core.risk.risk_manager import RiskManager, RiskParams


@dataclass
class StrategyConfig:
    """Strategy configuration.

    Defines the parameters and rules for an EA strategy.
    """

    name: str
    factors: List[str]
    risk_rules: List[str]
    params: Dict[str, Any] = field(default_factory=dict)

    # Factor weights (if using weighted combination)
    factor_weights: Optional[Dict[str, float]] = None

    # Factor combination method: 'weighted', 'equal', 'rank'
    combination_method: str = "rank"

    # Signal generation thresholds
    buy_threshold: float = 0.6
    sell_threshold: float = 0.4

    # Position sizing
    use_volatility_sizing: bool = True
    base_position_size: float = 0.01  # 1% of account

    # Filters
    min_confidence: float = 0.5
    session_filter: Optional[str] = None  # 'asian', 'london', 'newyork', None


@dataclass
class Signal:
    """Trading signal generated by strategy.

    Attributes:
        direction: 'BUY', 'SELL', or 'HOLD'
        confidence: Signal confidence (0 to 1)
        entry_price: Suggested entry price
        stop_loss: Stop loss price
        take_profit: Take profit price
        position_size: Suggested position size
        factors: Individual factor values used
        timestamp: Signal generation time
        reason: Human-readable signal reason
    """

    direction: str
    confidence: float
    entry_price: float
    stop_loss: float
    take_profit: float
    position_size: float
    factors: Dict[str, float]
    timestamp: datetime
    reason: str = ""


@dataclass
class MarketData:
    """Market data required for signal generation.

    Contains OHLCV data and additional market metrics.
    """

    symbol: str
    timestamp: datetime
    open_: float
    high: float
    low: float
    close: float
    volume: float = 0.0

    # Optional additional data
    bid: Optional[float] = None
    ask: Optional[float] = None
    bid_size: Optional[float] = None
    ask_size: Optional[float] = None

    # Volatility metrics
    current_volatility: Optional[float] = None
    historical_volatility: Optional[float] = None

    # Session info
    session: Optional[str] = None

    @classmethod
    def from_dict(cls, data: Dict) -> "MarketData":
        """Create MarketData from dictionary.

        Args:
            data: Dictionary with market data

        Returns:
            MarketData instance
        """
        return cls(
            symbol=data.get("symbol", "XAUUSD"),
            timestamp=data.get("timestamp", datetime.now()),
            open_=data.get("open", data.get("open_", data.get("close", 0))),
            high=data.get("high", data.get("close", 0)),
            low=data.get("low", data.get("close", 0)),
            close=data.get("close", 0),
            volume=data.get("volume", 0),
            bid=data.get("bid"),
            ask=data.get("ask"),
            bid_size=data.get("bid_size"),
            ask_size=data.get("ask_size"),
            current_volatility=data.get("current_volatility"),
            historical_volatility=data.get("historical_volatility"),
            session=data.get("session"),
        )

    def to_df(self) -> pd.DataFrame:
        """Convert to DataFrame for factor calculation.

        Returns:
            DataFrame with OHLC data
        """
        return pd.DataFrame(
            {
                "open": [self.open_],
                "high": [self.high],
                "low": [self.low],
                "close": [self.close],
                "volume": [self.volume],
            },
            index=[self.timestamp],
        )


class EAStrategyGenerator:
    """EA策略生成器.

    Generates trading signals using multi-factor analysis with risk management.

    Workflow:
    1. Calculate factor values from market data
    2. Combine factors using configured method
    3. Apply risk checks
    4. Generate trading signal with entry/exit levels
    """

    def __init__(
        self,
        config: StrategyConfig,
        factor_analyzer: Optional[FactorAnalyzer] = None,
        risk_manager: Optional[RiskManager] = None,
    ):
        """Initialize EA strategy generator.

        Args:
            config: Strategy configuration
            factor_analyzer: Optional factor analyzer for IC analysis
            risk_manager: Optional risk manager for pre-trade checks
        """
        self.config = config
        self.factor_analyzer = factor_analyzer or FactorAnalyzer()
        self.risk_manager = risk_manager or RiskManager()

        # Factor cache for performance
        self._factor_cache: Dict[str, pd.Series] = {}

        # Session detector
        self._session_times = {
            "asian": (0, 8),
            "london": (8, 16),
            "newyork": (13, 21),
        }

    def _detect_session(self, timestamp: datetime) -> str:
        """Detect trading session from timestamp.

        Args:
            timestamp: Trade timestamp

        Returns:
            Session name
        """
        hour = timestamp.hour
        for session, (start, end) in self._session_times.items():
            if start <= hour < end:
                return session
        return "offhours"

    def _calculate_factors(
        self, price_data: pd.DataFrame, active_factors: Optional[List[str]] = None
    ) -> Dict[str, pd.Series]:
        """Calculate factor values for price data.

        Args:
            price_data: DataFrame with OHLC data
            active_factors: List of factor names to calculate (None = use config)

        Returns:
            Dictionary of factor_name -> factor_series
        """
        factors_to_use = active_factors or self.config.factors
        results = {}

        for factor_name in factors_to_use:
            try:
                factor_func = get_factor_by_name(factor_name)
                results[factor_name] = factor_func(price_data["close"])
            except ValueError:
                # Handle multi-output factors
                if factor_name == "macd":
                    macd, signal, hist = FactorLibrary.macd(price_data["close"])
                    results["macd"] = macd
                    results["macd_signal"] = signal
                    results["macd_hist"] = hist
                elif factor_name == "stochastic":
                    k, d = FactorLibrary.stochastic(
                        price_data["high"],
                        price_data["low"],
                        price_data["close"],
                    )
                    results["stoch_k"] = k
                    results["stoch_d"] = d
                elif factor_name == "kdj":
                    k, d, j = FactorLibrary.kdj(
                        price_data["high"],
                        price_data["low"],
                        price_data["close"],
                    )
                    results["kdj_k"] = k
                    results["kdj_d"] = d
                    results["kdj_j"] = j

        return results

    def _combine_factors(
        self, factor_values: Dict[str, pd.Series]
    ) -> Tuple[pd.Series, Dict[str, float]]:
        """Combine multiple factors into a single signal.

        Args:
            factor_values: Dictionary of factor values

        Returns:
            Tuple of (combined_signal, latest_factor_values)
        """
        if self.config.combination_method == "rank":
            combined = FactorLibrary.combine_factors(
                factor_values, method="rank"
            )
        elif self.config.combination_method == "equal":
            combined = FactorLibrary.combine_factors(
                factor_values, method="equal"
            )
        else:  # weighted
            combined = FactorLibrary.combine_factors(
                factor_values, weights=self.config.factor_weights
            )

        # Get latest values for reporting
        latest_values = {
            name: series.iloc[-1] if len(series) > 0 else 0
            for name, series in factor_values.items()
        }

        return combined, latest_values

    def _apply_filters(self, signal: Signal, market_data: MarketData) -> Signal:
        """Apply session and confidence filters to signal.

        Args:
            signal: Generated signal
            market_data: Current market data

        Returns:
            Filtered signal
        """
        # Session filter
        if self.config.session_filter:
            current_session = market_data.session or self._detect_session(
                market_data.timestamp
            )
            if current_session != self.config.session_filter:
                return Signal(
                    direction="HOLD",
                    confidence=0.0,
                    entry_price=0,
                    stop_loss=0,
                    take_profit=0,
                    position_size=0,
                    factors={},
                    timestamp=market_data.timestamp,
                    reason=f"Session filter: expected {self.config.session_filter}, got {current_session}",
                )

        # Confidence filter
        if signal.confidence < self.config.min_confidence:
            return Signal(
                direction="HOLD",
                confidence=signal.confidence,
                entry_price=0,
                stop_loss=0,
                take_profit=0,
                position_size=0,
                factors=signal.factors,
                timestamp=market_data.timestamp,
                reason=f"Confidence {signal.confidence:.2%} below minimum {self.config.min_confidence:.2%}",
            )

        return signal

    def _calculate_stop_loss_take_profit(
        self,
        direction: str,
        entry_price: float,
        market_data: MarketData,
    ) -> Tuple[float, float]:
        """Calculate stop loss and take profit levels.

        Args:
            direction: Trade direction ('BUY' or 'SELL')
            entry_price: Entry price
            market_data: Market data for volatility adjustment

        Returns:
            Tuple of (stop_loss, take_profit)
        """
        stop_loss_pct = self.risk_manager.params.stop_loss
        take_profit_pct = self.risk_manager.params.take_profit

        # Volatility adjustment
        if self.config.use_volatility_sizing:
            if (
                market_data.current_volatility
                and market_data.historical_volatility
                and market_data.historical_volatility > 0
            ):
                vol_ratio = (
                    market_data.current_volatility / market_data.historical_volatility
                )
                # Widen stops in high volatility
                if vol_ratio > 1.5:
                    stop_loss_pct *= vol_ratio
                    take_profit_pct *= vol_ratio

        if direction == "BUY":
            stop_loss = entry_price * (1 - stop_loss_pct)
            take_profit = entry_price * (1 + take_profit_pct)
        else:
            stop_loss = entry_price * (1 + stop_loss_pct)
            take_profit = entry_price * (1 - take_profit_pct)

        return stop_loss, take_profit

    def _calculate_entry_price(
        self, market_data: MarketData, direction: str
    ) -> float:
        """Calculate entry price based on market data.

        Args:
            market_data: Current market data
            direction: Trade direction

        Returns:
            Entry price
        """
        # Use mid price if available, otherwise close
        if market_data.bid and market_data.ask:
            mid = (market_data.bid + market_data.ask) / 2
        else:
            mid = market_data.close

        # For market orders, use slightly worse price
        if direction == "BUY":
            # Buy slightly above mid (assuming ask)
            return market_data.ask if market_data.ask else mid * 1.0001
        else:
            # Sell slightly below mid (assuming bid)
            return market_data.bid if market_data.bid else mid * 0.9999

    def generate_signal(
        self,
        market_data: Dict | MarketData,
        active_factors: Optional[List[str]] = None,
        account_balance: float = 1.0,
    ) -> Signal:
        """生成交易信号.

        Main entry point for signal generation.

        Args:
            market_data: Market data (dict or MarketData)
            active_factors: Override active factors (None = use config)
            account_balance: Account balance for position sizing

        Returns:
            Signal with direction, confidence, entry/exit levels
        """
        # Convert to MarketData if dict
        if isinstance(market_data, dict):
            market_data = MarketData.from_dict(market_data)

        # Create price DataFrame
        price_df = market_data.to_df() if not isinstance(market_data, MarketData) else market_data.to_df()

        # 1. Calculate factor values
        factor_values = self._calculate_factors(price_df, active_factors)

        # 2. Combine factors
        combined_signal, latest_factors = self._combine_factors(factor_values)

        # Get latest combined value
        if len(combined_signal) > 0:
            signal_value = combined_signal.iloc[-1]
        else:
            signal_value = 0.5  # Neutral

        # 3. Determine direction based on thresholds
        if signal_value >= self.config.buy_threshold:
            direction = "BUY"
            confidence = (signal_value - self.config.buy_threshold) / (
                1 - self.config.buy_threshold
            )
        elif signal_value <= self.config.sell_threshold:
            direction = "SELL"
            confidence = (self.config.sell_threshold - signal_value) / self.config.sell_threshold
        else:
            direction = "HOLD"
            confidence = 1 - abs(signal_value - 0.5) * 2

        # 4. Calculate entry price
        entry_price = self._calculate_entry_price(market_data, direction)

        # 5. Calculate stop loss and take profit
        stop_loss, take_profit = self._calculate_stop_loss_take_profit(
            direction, entry_price, market_data
        )

        # 6. Calculate position size
        stop_loss_pct = abs(entry_price - stop_loss) / entry_price
        position_size = self.risk_manager.calculate_position_size(
            signal_confidence=confidence,
            account_balance=account_balance,
            stop_loss_pct=stop_loss_pct,
            current_volatility=market_data.current_volatility,
            historical_volatility=market_data.historical_volatility,
        )

        # 7. Create base signal
        signal = Signal(
            direction=direction,
            confidence=min(confidence, 1.0),
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            position_size=position_size,
            factors=latest_factors,
            timestamp=market_data.timestamp,
            reason="",
        )

        # 8. Apply filters
        signal = self._apply_filters(signal, market_data)

        # 9. Pre-trade risk check
        if signal.direction != "HOLD":
            order = {
                "symbol": market_data.symbol,
                "direction": signal.direction,
                "price": signal.entry_price,
                "position_size": signal.position_size,
                "timestamp": market_data.timestamp,
            }

            risk_result = self.risk_manager.pre_trade_check(
                order=order,
                current_equity=account_balance,
                current_volatility=market_data.current_volatility,
                historical_volatility=market_data.historical_volatility,
            )

            if not risk_result.allowed:
                return Signal(
                    direction="HOLD",
                    confidence=0.0,
                    entry_price=0,
                    stop_loss=0,
                    take_profit=0,
                    position_size=0,
                    factors=latest_factors,
                    timestamp=market_data.timestamp,
                    reason=f"Risk check failed: {risk_result.rejection_reason}",
                )

            if risk_result.adjusted_position_size:
                signal.position_size = risk_result.adjusted_position_size

            signal.reason = "Risk-adjusted signal" if risk_result.warnings else "Signal generated"

        return signal

    def backtest_signal(
        self,
        price_data: pd.DataFrame,
        active_factors: Optional[List[str]] = None,
    ) -> pd.DataFrame:
        """Generate signals for historical data (backtesting).

        Args:
            price_data: DataFrame with OHLC data and timestamp index
            active_factors: List of factors to use

        Returns:
            DataFrame with signals and factor values
        """
        results = []

        for i in range(50, len(price_data)):  # Need warmup period
            window_data = price_data.iloc[:i]
            market_data = MarketData(
                symbol="XAUUSD",
                timestamp=price_data.index[i],
                open_=price_data.iloc[i]["open"],
                high=price_data.iloc[i]["high"],
                low=price_data.iloc[i]["low"],
                close=price_data.iloc[i]["close"],
                volume=price_data.iloc[i].get("volume", 0),
            )

            signal = self.generate_signal(
                market_data=market_data,
                active_factors=active_factors,
            )

            results.append(
                {
                    "timestamp": market_data.timestamp,
                    "close": market_data.close,
                    "signal": signal.direction,
                    "confidence": signal.confidence,
                    "position_size": signal.position_size,
                    **{f"factor_{k}": v for k, v in signal.factors.items()},
                }
            )

        return pd.DataFrame(results)

    def optimize_thresholds(
        self,
        price_data: pd.DataFrame,
        returns: pd.Series,
        factor_names: Optional[List[str]] = None,
    ) -> Dict:
        """Optimize signal thresholds based on historical performance.

        Args:
            price_data: Historical price data
            returns: Forward returns
            factor_names: Factors to analyze

        Returns:
            Dictionary with optimized parameters
        """
        # Generate signals with different thresholds
        threshold_grid = [
            (0.7, 0.3),
            (0.65, 0.35),
            (0.6, 0.4),
            (0.55, 0.45),
            (0.5, 0.5),
        ]

        best_ic = -1
        best_thresholds = (0.6, 0.4)

        for buy_th, sell_th in threshold_grid:
            self.config.buy_threshold = buy_th
            self.config.sell_threshold = sell_th

            signals_df = self.backtest_signal(price_data, factor_names)
            if signals_df.empty:
                continue

            # Calculate IC
            signal_values = signals_df["confidence"].values
            aligned_returns = returns.iloc[-len(signal_values) :]

            if len(signal_values) > 30:
                ic = np.corrcoef(signal_values, aligned_returns.values)[0, 1]
                if ic > best_ic:
                    best_ic = ic
                    best_thresholds = (buy_th, sell_th)

        return {
            "best_buy_threshold": best_thresholds[0],
            "best_sell_threshold": best_thresholds[1],
            "best_ic": best_ic,
        }


def create_default_strategy() -> StrategyConfig:
    """Create a default XAUUSD strategy configuration.

    Returns:
        StrategyConfig with sensible defaults for gold trading
    """
    return StrategyConfig(
        name="XAUUSD_Default",
        factors=[
            "momentum",
            "rsi",
            "macd",
            "volatility",
            "atr",
            "bollinger_position",
        ],
        risk_rules=["max_drawdown", "stop_loss", "take_profit", "position_size"],
        params={
            "lookback_period": 20,
            "session": None,
        },
        factor_weights={
            "momentum": 0.25,
            "rsi": 0.20,
            "macd": 0.20,
            "volatility": 0.15,
            "atr": 0.10,
            "bollinger_position": 0.10,
        },
        combination_method="weighted",
        buy_threshold=0.6,
        sell_threshold=0.4,
        min_confidence=0.5,
        base_position_size=0.01,
        use_volatility_sizing=True,
    )
